-- RAW table 
CREATE TABLE IF NOT EXISTS `innov-jrfr-fizq-1.ach_bc50_raw.ach_data_raw` ( int64_field_0 INT64, 
	customer_identifier INT64, 
	bank_client_name STRING, 
	customer_account INT64, 
	customer_account_type STRING, 
	customer_funds_indicator BOOL, 
	transaction_counterparty STRING, 
	debit_party_identifier STRING, 
	debit_financial_institution STRING, 
	transaction_processor_party STRING, 
	transaction_processor_party_role STRING, 
	credit_party_identifier STRING, 
	credit_bank STRING, 
	transaction_flow_direction STRING, 
	ach_company_identifier INT64, 
	file_owner_id STRING, 
	ach_company_name STRING, 
	external_company_name STRING, 
	file_identifier INT64, 
	ach_settlement_account INT64, 
	transaction_class_code STRING, 
	movement_type_indicator STRING, 
	source_account_identifier INT64, 
	payee_identifier STRING, 
	payee_identifier_label STRING, 
	posting_date DATE, 
	originator_routing_number INT64, 
	receiver_routing_number INT64, 
	originator_bank STRING, 
	receiver_bank STRING, 
	batch_text STRING, 
	entry_code STRING, 
	transaction_amount FLOAT64, 
	batch_comment_text STRING, 
	transaction_text STRING, 
	payment_interval STRING, 
	perfect_receivable INT64, 
	batch_post_identifier INT64, 
	file_distribution_reference INT64, 
	sequence_number INT64, 
	perfect_receivable_account_number FLOAT64, 
	perfect_receivable_company_name STRING, 
	target_account_number FLOAT64, 
	target_account_type STRING, 
	conc_payment_group INT64, 
	top_20 BOOL, 
	DIRTY_APPLIED_50PCT BOOL, 
	originator_bank_imp STRING, 
	receiver_bank_imp STRING, 
	transaction_counterparty_imp STRING, 
	DIRTY_TAGS STRING ) PARTITION BY posting_date;






