-- RAW table 
CREATE TABLE IF NOT EXISTS `innov-jrfr-fizq-1.ach_bc50_raw.ach_data_raw` ( int64_field_0 INT64, 
	customer_identifier STRING, 
	bank_client_name STRING, 
	customer_account STRING, 
	customer_account_type STRING, 
	customer_funds_indicator STRING, 
	transaction_counterparty STRING, 
	debit_party_identifier STRING, 
	debit_party STRING, 
	debit_financial_institution STRING, 
	transaction_processor_party STRING, 
	transaction_processor_party_role STRING, 
	credit_party_identifier STRING, 
	credit_party STRING, 
	credit_bank STRING, 
	transaction_flow_direction STRING, 
	ach_company_identifier STRING, 
	file_owner_id STRING, 
	ach_company_name STRING, 
	external_company_name STRING, 
	file_identifier STRING, 
	ach_settlement_account STRING, 
	transaction_class_code STRING, 
	movement_type_indicator STRING, 
	source_account_identifier STRING, 
	payee_identifier STRING, 
	payee_identifier_label STRING, 
	posting_date STRING, 
	originator_routing_number STRING, 
	receiver_routing_number STRING, 
	originator_bank STRING, 
	receiver_bank STRING, 
	batch_text STRING, 
	entry_code STRING, 
	transaction_amount STRING, 
	batch_comment_text STRING, 
	transaction_text STRING, 
	payment_interval STRING, 
	perfect_receivable STRING, 
	batch_post_identifier STRING, 
	file_distribution_reference STRING, 
	sequence_number STRING, 
	perfect_receivable_account_number STRING, 
	perfect_receivable_company_name STRING, 
	target_account_number STRING, 
	target_account_type STRING, 
	conc_payment_group STRING, 
	top_20 STRING, 
	DIRTY_APPLIED_50PCT STRING, 
	originator_bank_imp STRING, 
	receiver_bank_imp STRING, 
	transaction_counterparty_imp STRING, 
	DIRTY_TAGS STRING );






